name: number checker action
description: check number wheather it is even or not.
imputs:
   target-number:
      description: number to check
      required: true
      default: '1'
outputs:
   result:
      description: boolean result for number even test.
runs:
   using: docker
   image: Dockerfile
   args:
   - ${{ inputs.target-number }}
